name: pre-commit

on:
  merge_group: ~
  workflow_dispatch: ~
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: elastic/oblt-actions/pre-commit@31fd8582a94d1829536be22c624697f851fdf60e # v1
